global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/pipeline_alerts.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # REMOVED: - job_name: 'kafka'
  - job_name: 'mnemo_quant_ingestion'
    static_configs:
      - targets: ['quant-mnemo:8001']
  - job_name: 'mnemo_quant_storage'
    static_configs:
      - targets: ['quant-mnemo-api:8002']